apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - evidence-api.yaml
  - edge-agent.yaml
  - web-ui.yaml
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
